mybackpack/config/routes.rb
Rails.application.routes.draw do
  resources :item_types
  resources :route_menus
  resources :route_items
  resources :user_available_items
  resources :user_favorite_foods
  resources :meals
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :profiles
  resources :physical_conditions
  devise_for :users
  get '/user_articles', to: 'articles#user_articles'
  get '/user_routes', to: 'routes#user_routes'
  root to: "articles#index"

  resources :route_statuses
  resources :items
  resources :weather_types
  resources :object_categories
  resources :object_importances
  resources :seasons
  resources :routes
  resources :complexities
  resources :settlements
  resources :settlement_types
  resources :chains
  resources :create_settlements
  resources :food_types
  resources :foods
  resources :food_categories
  resources :producers
  resources :article_categories
  resources :articles
  get '/one_backpack', to: 'problems#one_backpack'
  get '/multiple_backpack', to: 'problems#multiple_backpack'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mybackpack/app/models/food.rb
# frozen_string_literal: true

# Class Food
class Food < ApplicationRecord
  validates :title, length: { maximum: 200 }, presence: true
  validates :source, presence: true
  validates :description, presence: true
  validates :caloric, presence: true # 100 g
  validates :weight, presence: true # kg
  validates :volume, presence: true # l

  belongs_to :food_type
  belongs_to :food_category
  belongs_to :producer

  has_many :user_favorite_foods
  has_many :users, through: :user_favorite_foods

  has_many :route_menus
  has_many :route_meals, through: :route_menus, source: :meals
  has_many :route_users, through: :route_menus, source: :users
  has_many :routes, through: :route_menus
end

mybackpack/app/models/food_type.rb
# frozen_string_literal: true

# Class Food Type
class FoodType < ApplicationRecord
  validates :title, length: { maximum: 200 }, presence: true

  has_many :food
end

mybackpack/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  def index
    @foods = Food.all
  end

  def show; end

  def new
    @food = Food.new
  end

  def edit; end

  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.require(:food).permit(:title, :description, :source, :caloric, :weight,
        :volume, :food_type_id, :food_category_id, :producer_id)
    end
end

mybackpack/app/helpers/foods_helper.rb
module FoodsHelper
end

mybackpack/app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :caloric %>
    <%= form.text_field :caloric %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :volume %>
    <%= form.text_field :volume %>
  </div>

  <div class="select">
    <%= form.label :food_type %>
    <%= form.collection_select(:food_type_id, FoodType.all, :id, :title) %>
  </div>

  <div class="select">
    <%= form.label :food_category %>
    <%= form.collection_select(:food_category_id, FoodCategory.all, :id, :title) %>
  </div>

  <div class="select">
    <%= form.label :producer %>
    <%= form.collection_select(:producer_id, Producer.all, :id, :title) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

mybackpack/app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

mybackpack/app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<div>
  <p><%= link_to 'Food Types', food_types_path %> |
  <%= link_to 'Food Categories', food_categories_path %> |
  <%= link_to 'Producer', producers_path %> </p>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.title %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

mybackpack/app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

mybackpack/app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @food.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Source:</strong>
  <%= @food.source %>
</p>

<p>
  <strong>Caloric:</strong>
  <%= @food.caloric %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @food.weight %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @food.volume %>
</p>

<p>
  <strong>Food Type:</strong>
  <%= @food.food_type.title %>
</p>

<p>
  <strong>Food Category:</strong>
  <%= @food.food_category.title %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @food.producer.title %>
</p>


<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>