mybackpack/config/routes.rb
Rails.application.routes.draw do
  resources :item_types
  resources :route_menus
  resources :route_items
  resources :user_available_items
  resources :user_favorite_foods
  resources :meals
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :profiles
  resources :physical_conditions
  devise_for :users
  get '/user_articles', to: 'articles#user_articles'
  get '/user_routes', to: 'routes#user_routes'
  root to: "articles#index"

  resources :route_statuses
  resources :items
  resources :weather_types
  resources :object_categories
  resources :object_importances
  resources :seasons
  resources :routes
  resources :complexities
  resources :settlements
  resources :settlement_types
  resources :chains
  resources :create_settlements
  resources :food_types
  resources :foods
  resources :food_categories
  resources :producers
  resources :article_categories
  resources :articles
  get '/one_backpack', to: 'problems#one_backpack'
  get '/multiple_backpack', to: 'problems#multiple_backpack'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mybackpack/app/models/route.rb
# frozen_string_literal: true

# Class Route
class Route < ApplicationRecord
  validates :title, length: { maximum: 200 }, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :duration, presence: true

  # validates :chain_id, presence: true
  # validates :user_id, presence: true
  # validates :complexity_id, presence: true
  validates :settlement_dep, presence: true
  validates :settlement_arr, presence: true

  scope :published, -> { where(published: true) }
  scope :settlement_title, ->(id) { Settlement.find(id).title }

  belongs_to :chain
  belongs_to :complexity
  belongs_to :route_status
  belongs_to :user

  has_many :route_place
  has_many :settlement, through: :route_place

  has_many :route_items
  has_many :routes_items, through: :route_items, source: :items
  has_many :users_items, through: :route_items, source: :users

  has_many :route_menus
  has_many :route_meals, through: :route_menus, source: :meals
  has_many :route_foods, through: :route_menus, source: :foods
end

mybackpack/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
    @user_items = RouteItem.items(@route.id, current_user.id)
    @categories = UserAvailableItem.item_categories(@user_items)
  end

  def new
    @route = Route.new
  end

  def edit; end

  def create
    @route = Route.new(route_params)
    @route.user_id = current_user.id

    respond_to do |format|
      if @route.save
        # format.html { redirect_to @route, notice: 'Route was successfully created.' }
        # format.html { redirect_to new_route_item_path }
        format.html { redirect_to :controller => 'route_items', :action => 'new', route: @route.id, rp: route_part }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_routes
    @routes = current_user.routes.all
  end

  private

    def set_route
      @route = Route.find(params[:id])
    end

    def route_params
      params.require(:route).permit(:title, :description, :start_date, :end_date, :duration, :chain_id, :complexity_id, :publication, :settlement_dep, :settlement_arr,
        :route_status_id)
    end

    def route_part
      params.require(:route).permit(participants: [])
    end
end

mybackpack/app/helpers/routes_helper.rb
module RoutesHelper
end

mybackpack/app/views/routes/_form.html.erb
<%= form_with(model: route, local: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, for: 'Title', value: 'Назва', class: 'bmd-label-floating'  %>
    <%= form.text_field :title, class: 'form-control', id: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.label :description, for: 'Description',  value: 'Опис', class: 'bmd-label-floating'  %>
    <%= form.text_area :description, class: 'form-control', id: 'Description' %>
  </div>

  <div class="form-group">
    <%= form.label :start_date, for: 'Startdate',  value: 'Дата початку', class: 'bmd-label-floating'  %>
    <!--<%= form.datetime_select :start_date, class: 'form-control', id: 'Startdate' %> --->
    <%= form.date_field :start_date, class: 'form-control', id: 'Startdate' %>
  </div>

  <div class="form-group">
    <%= form.label :end_date, for: 'Enddate',  value: 'Дата закінчення', class: 'bmd-label-floating'  %>
    <%= form.date_field :end_date, class: 'form-control', id: 'Enddate' %>
  </div>

  <div class="form-group">
    <%= form.label :duration, for: 'Duration',  value: 'Тривалість', class: 'bmd-label-floating'  %>
    <%= form.number_field :duration, class: 'form-control', id: 'Duration' %>
  </div>

  <div class="form-group">
    <%= form.label :chain_id, value: 'Chain',  value: 'Гірський хребет', class: 'bmd-label-floating' %>
    <%= form.select(:chain_id, options_from_collection_for_select(Chain.all.sort_by{ |c| c.title }, :id, :title, {:selected => route.chain_id}), {}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :complexity_id, value: 'Complexity',  value: 'Важкість', class: 'bmd-label-floating' %>
    <%= form.select(:complexity_id, options_from_collection_for_select(Complexity.all.sort_by{ |c| c.title }, :id, :title, {:selected => route.complexity_id}), {}, {:class => 'form-control'})%>
  </div>


  <div class="form-group">
    <%= form.label :publication, value: 'Публікація' %>
    <%= form.check_box :publication %>
  </div>

  <div class="form-group">
    <%= form.label :settlement_dep, value: 'Departure',  value: 'Місце відправлення', class: 'bmd-label-floating' %>
    <%= form.select(:settlement_dep, options_from_collection_for_select(Settlement.all.sort_by{ |c| c.title }, :id, :title, {:selected => route.settlement_dep}), {}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :settlement_arr, value: 'Arrival',  value: 'Місце прибуття', class: 'bmd-label-floating' %>
    <%= form.select(:settlement_arr, options_from_collection_for_select(Settlement.all.sort_by{ |c| c.title }, :id, :title, {:selected => route.settlement_arr}), {}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :route_status_id, value: 'Route status',  value: 'Статус', class: 'bmd-label-floating' %>
    <%= form.select(:route_status_id, options_from_collection_for_select(RouteStatus.all.sort_by{ |c| c.title }, :id, :title, {:selected => route.route_status_id}), {}, {:class => 'form-control'})%>
  </div>

  <div>
    <%= form.label :participants, value: 'Учасники', class: 'bmd-label-floating' %>
    <%= form.select(:participants, options_from_collection_for_select(Profile.all.sort_by{ |p| p.last_name }.sort_by{ |p| p.first_name }, :id, :full_name), {}, {:class => 'form-control', :multiple => true })%>

<!--     <select class="mdb-select md-form" multiple>
  <option value="" disabled selected>Choose your country</option>
  <option value="1">USA</option>
  <option value="2">Germany</option>
  <option value="3">France</option>
  <option value="3">Poland</option>
  <option value="3">Japan</option>
</select>
<label class="mdb-main-label">Label example</label>
<button class="btn-save btn btn-primary btn-sm">Save</button> -->
  </div>


  <div class="actions">
    <%= form.submit value: 'Створити',  class: 'btn btn-primary btn-raised'%>
  </div>
<% end %>

mybackpack/app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

mybackpack/app/views/routes/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Маршрути</h1>

<br>
<%= link_to 'Створити новий маршрут', new_route_path %>
<br>

<div>
  <% @routes.each do |route| %>
    <div>
      <h4><%= route.title %></h4>
      <p><%= route.chain.title %></p>
      <p><%= truncate(route.description, :length => 200, :separator => ' ')%> <%= link_to 'Читати більше', route %></p>
    </div>
  <% end %>
</div>

mybackpack/app/views/routes/new.html.erb
<h1>Створення нового маршруту</h1>

<%= render 'form', route: @route %>

<%= link_to 'Повернутися', routes_path %>
<div style="margin-bottom: 30px;"></div>

mybackpack/app/views/routes/route_item.html.erb
<h1>Hi</h1>

mybackpack/app/views/routes/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h2><%= @route.title %></h2>

<div style="margin-bottom: 15px;">
  <%= @route.description %>
</div>

<div>
  <p><strong>Складність:</strong> <%= @route.complexity.title %></p>
</div>

<div>
  <p>
    <strong>З</strong> <%= @route.start_date.strftime("%d %b %Y") %>
    <strong>до</strong> <%= @route.end_date.strftime("%d %b %Y")  %>,
    <strong>тривалість</strong> <%= @route.duration %> дні
  </p>
</div>

<div>
  <p><strong>Гірський хребет:</strong> <%= @route.chain.title %></p>
</div>

<!--<p>
  <strong>Author:</strong>
  <%= @route.user_id %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @route.publication %>
</p>-->

<div>
  <p>
    <strong>Місце початку:</strong>
    <%= Settlement.full_title(Settlement.find(@route.settlement_dep)) %>
  </p>
</div>

<div>
  <p>
    <strong>Місце закінчення:</strong>
    <%= Settlement.full_title(Settlement.find(@route.settlement_arr)) %>
  </p>
</div>

<div>
  <h3>Моє спорядження (<%= Profile.find(current_user.id).first_name %> <%= Profile.find(current_user.id).last_name %>)*</h3>

  <% sum = 0 %>
<div>
<% @categories.each do |category| %>
  <p><strong><%= category %></strong></p>
  <table>
    <thead>
      <tr>
        <th style="width: 250px">Предмет</th>
        <th>Кількість</th>
        <th>Вага (кг)</th>
        <th>Ідивідуальність</th>
        <th>Важливість</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% UserAvailableItem.category_items(@user_items, category).each do |i| %>
        <tr>
          <% sum += i.item.weight %>
          <td><%= i.item.title %></td>
          <td><%= 1 %></td>
          <td><%= i.item.weight %></td>
          <td>
            <% if i.item.individualy %>
              індивідуальна
            <% else %>
              групова
            <% end %>
          </td>
          <td><%= i.item.object_importance.title %></td>
          <td><%= link_to 'Деальніше', item_path(i.item) %></td>
          <!-- <td><%= link_to 'Редагувати', edit_user_available_item_path(i) %></td> -->
          <!-- <td><%= link_to 'Destroy', i, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
<% end %>
  <div>
    <h4>Вага наплічника: <%= sum.round(2) %> кг</h4>
  </div>

  <p style="font-weight: bold; font-size: 18px;">*Даний список спорядження є рекомендованим, а не обов'язковим.</p>
</div>


<%= link_to 'Редагувати', edit_route_path(@route) %> |
<%= link_to 'Повернутися', routes_path %>
<div style="margin-bottom: 30px;"></div>

mybackpack/app/views/routes/user_routes.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="row">

<div class="col-md-2"></div>
<div class="col-md-3">
<h3 style="margin-bottom: 30px; margin-left: -50px">Профіль</h3>
</div>
<div class="col-md-7"></div>

<div>

<div class="row" style="width: 900px; align-content: center;">
<div class="col-md-2"></div>
<div class="col-md-3">
  <!-- <p><%= link_to 'User available items', user_available_items_path %></p> -->
  <!-- <p><%= link_to 'User favorite foods', user_favorite_foods_path %></p> -->
<!--   <p><%= link_to 'User routes', user_routes_path %></p>
  <p><%= link_to 'User articles', user_articles_path %></p> -->

  <p style="font-size: 20px"><%= link_to 'Мої дані', profile_path(current_user.id) %></p>
  <p style="font-size: 20px"><%= link_to 'Мої статті', user_articles_path %></p>
  <p style="font-size: 20px"><%= link_to 'Мої маршрути', user_routes_path %></p>
  <p style="font-size: 20px"><%= link_to 'Моє спродяження', user_available_items_path %></p>
</div>

<div class="col-md-7" >

  <h4 style="margin-bottom: 30px">Мої маршрути</h4>

  <%= link_to 'Створити новий маршрут', new_route_path %>
  <p style="margin-bottom: 30px"></p>

  <div>
    <% @routes.each do |route| %>
    <div style="margin-bottom: 25px">
      <p style="font-size: 16px; font-style: italic; font-weight: bold;">
        <%= link_to route.title, route_path(route) %>
      </p>
      <p><%= truncate(route.description, :length => 200, :separator => ' ') %> <%= link_to 'Читати більше', route %></p>
      <!-- <p>Гірський хребет: <%= route.chain.title %></p> -->
      <p>Початок: <%= route.start_date.strftime("%d %b %Y") %>, <%= Settlement.full_title(Settlement.find(route.settlement_dep)) %> | Закінчення: <%= route.end_date.strftime("%d %b %Y") %>, <%= Settlement.full_title(Settlement.find(route.settlement_arr)) %></p>
    </div>
    <% end %>
  </div>

</div>
</div>