mybackpack/config/routes.rb
Rails.application.routes.draw do
  resources :item_types
  resources :route_menus
  resources :route_items
  resources :user_available_items
  resources :user_favorite_foods
  resources :meals
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :profiles
  resources :physical_conditions
  devise_for :users
  get '/user_articles', to: 'articles#user_articles'
  get '/user_routes', to: 'routes#user_routes'
  root to: "articles#index"

  resources :route_statuses
  resources :items
  resources :weather_types
  resources :object_categories
  resources :object_importances
  resources :seasons
  resources :routes
  resources :complexities
  resources :settlements
  resources :settlement_types
  resources :chains
  resources :create_settlements
  resources :food_types
  resources :foods
  resources :food_categories
  resources :producers
  resources :article_categories
  resources :articles
  get '/one_backpack', to: 'problems#one_backpack'
  get '/multiple_backpack', to: 'problems#multiple_backpack'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mybackpack/app/models/item.rb
# frozen_string_literal: true

# Class Item
class Item < ApplicationRecord
  validates :title, length: { maximum: 200 }, presence: true
  validates :description, presence: true
  validates :source, presence: true
  validates :weight, presence: true # kg
  validates :volume, presence: true # l

  belongs_to :object_category
  belongs_to :item_type
  belongs_to :object_importance
  belongs_to :producer
  belongs_to :season
  has_many :items_weather_type
  has_many :weather_type, through: :items_weather_type

  has_many :user_available_items
  has_many :users, through: :user_available_items

  has_many :route_items
  has_many :routes, through: :route_items, source: :routes
  has_many :users_items, through: :route_items, source: :users
end

mybackpack/app/models/item_type.rb
# frozen_string_literal: true

# Class Item Type
class ItemType < ApplicationRecord
  validates :title, length: { maximum: 200 }, presence: true

  has_many :item
end

mybackpack/app/controllers/items_controller.rb
# frozen_string_literal: true

# Conroller class Item
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show; end

  def new
    @item = Item.new
  end

  def edit; end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :weight, :volume, :description, :source, :individualy,
      :object_category_id, :item_type_id, :object_importance_id, :season_id, :producer_id,
      weather_type_ids: [])
  end
end

mybackpack/app/helpers/items_helper.rb
module ItemsHelper
end

mybackpack/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, for: 'Title', class: 'bmd-label-floating' %>
    <%= form.text_field :title, class: 'form-control', id: 'Title' %>
    <span class="bmd-help">We'll never share your email with anyone else.</span>
  </div>

  <div class="form-group">
    <%= form.label :description, for: 'Description', class: 'bmd-label-floating' %>
    <%= form.text_area :description, class: 'form-control', id: 'Description' %>
    <span class="bmd-help">We'll never share your email with anyone else.</span>
  </div>

  <div class="form-group">
    <%= form.label :weight, for: 'Weight', class: 'bmd-label-floating' %>
    <%= form.text_field :weight, class: 'form-control', id: 'Weight' %>
    <span class="bmd-help">We'll never share your email with anyone else.</span>
  </div>

  <div class="form-group">
    <%= form.label :volume, for: 'Volume', class: 'bmd-label-floating' %>
    <%= form.text_field :volume, class: 'form-control', id: 'Volume' %>
    <span class="bmd-help">We'll never share your email with anyone else.</span>
  </div>

  <div class="form-group">
    <%= form.label :source, for: 'Source', class: 'bmd-label-floating' %>
    <%= form.text_field :source, class: 'form-control', id: 'Source' %>
    <span class="bmd-help">We'll never share your email with anyone else.</span>
  </div>

  <div class="checkbox">
    <label><%= form.check_box :individualy %> Individual</label>
  </div>

  <div class="form-group">
    <%= form.label :object_category_id, value: 'Object category', class: 'bmd-label-floating' %>
    <%= form.select(:object_category_id, options_from_collection_for_select(ObjectCategory.all.sort_by{ |c| c.title }, :id, :title, {:selected => item.object_category_id}), {}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :item_type_id, value: 'Item type', class: 'bmd-label-floating' %>
    <%= form.select(:item_type_id, options_from_collection_for_select(ItemType.all.sort_by{ |c| c.title }, :id, :title, {:selected => item.item_type_id}), {}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :object_importance_id, value: 'Object importance', class: 'bmd-label-floating' %>
    <%= form.select(:object_importance_id, options_from_collection_for_select(ObjectImportance.all.sort_by{ |c| c.title }, :id, :title, {:selected => item.object_importance_id}), {}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :season_id, value: 'Season', class: 'bmd-label-floating' %>
    <%= form.select(:season_id, options_from_collection_for_select(Season.all.sort_by{ |c| c.title }, :id, :title, {:selected => item.season_id}), {}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :weather_type %><br />
    <div class="row">
      <% WeatherType.all.sort_by{ |w| w.title }.each do |type| %>
      <div class="col-md-3">
        <%= check_box_tag "item[weather_type_ids][]", type.id,
          @item.weather_type.include?(type) %>
        <%= type.title %><br />
      </div>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :producer_id, value: 'Producer', class: 'bmd-label-floating' %>
    <%= form.select(:producer_id, options_from_collection_for_select(Producer.all.sort_by{ |c| c.title }, :id, :title, {:selected => item.producer_id}), {}, {:class => 'form-control'})%>
  </div>

  <div>
    <%= link_to 'Back', items_path, class: "btn btn-default" %>
    <%= form.submit class: 'btn btn-primary btn-raised' %>
  </div>
<% end %>

mybackpack/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

mybackpack/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Спорядження</h1>

<div>
  <p>
<!--   <%= link_to 'Season', seasons_path %> |
  <%= link_to 'Item Importance', object_importances_path %> |
  <%= link_to 'Item Category', object_categories_path %> |
  <%= link_to 'Weather Type', weather_types_path %> | -->
  <%= link_to 'Виробники', producers_path %>
  </p>
</div>

<!--<% if current_user %>
<%= link_to 'Додати нове спорядження', new_item_path %>
<% end %>-->

  <div>
    <% @items.each do |item| %>
      <div>
        <h4><%= item.title %></h4>
        <p><%= truncate(item.description, :length => 200, :separator => ' ')%> <%= link_to 'Читати більше', item %></p>
        <p>Виробник: <%= item.producer.title %> | <%= link_to 'Купити', item.source %></p>
      </div>
    <% end %>
  </div>

mybackpack/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

mybackpack/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @item.title %></h2>

<p>
  <strong>Вага:</strong>
  <%= @item.weight %>
  кг
</p>

<p>
  <strong>Об'єм:</strong>
  <%= @item.volume %>
  л
</p>

<p>
  <strong>Опис:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Категорія:</strong>
  <%= @item.object_category.title %>
</p>

<p>
  <strong>Тип:</strong>
  <%= @item.item_type.title %>
</p>

<p>
  <strong>Сезон:</strong>
  <%= @item.season.title %>
</p>

<p>
  <strong>Найкраще підходить для погоди: </strong>
    <% @item.weather_type.each do |type| %>
    <%= link_to type.title, weather_type_path(type) %>
    <% end %>
</p>

<p>
  <strong>Виробник:</strong>
  <%= @item.producer.title %>
</p>

<p>
  <strong>Індивідуальність речі:</strong>
  <% if @item.individualy %>
    індивідуальна
  <% else %>
    групова
  <% end %>
</p>

<p>
  <strong>Важливість:</strong>
  <%= @item.object_importance.title %>
</p>

<p>
  <strong>Джерело:</strong>
  <%= link_to @item.source, @item.source %>
</p>

<!-- <%= link_to 'Редагувати', edit_item_path(@item) %> | -->
<%= link_to 'Назад', items_path %>