mybackpack/config/routes.rb
Rails.application.routes.draw do
  resources :item_types
  resources :route_menus
  resources :route_items
  resources :user_available_items
  resources :user_favorite_foods
  resources :meals
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :profiles
  resources :physical_conditions
  devise_for :users
  get '/user_articles', to: 'articles#user_articles'
  get '/user_routes', to: 'routes#user_routes'
  root to: "articles#index"

  resources :route_statuses
  resources :items
  resources :weather_types
  resources :object_categories
  resources :object_importances
  resources :seasons
  resources :routes
  resources :complexities
  resources :settlements
  resources :settlement_types
  resources :chains
  resources :create_settlements
  resources :food_types
  resources :foods
  resources :food_categories
  resources :producers
  resources :article_categories
  resources :articles
  get '/one_backpack', to: 'problems#one_backpack'
  get '/multiple_backpack', to: 'problems#multiple_backpack'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mybackpack/app/models/user_available_item.rb
# frozen_srting_literal: true

# class User Available Item
class UserAvailableItem < ApplicationRecord
  belongs_to :user
  belongs_to :item

  def self.item_categories(items)
    categories = []
    items.each do |i|
      categories.push(i.item.object_category.title)
    end
    categories.uniq
  end

  def self.category_items(items, category)
    i_arr = []
    items.each do |i|
      i_arr.push(i) if i.item.object_category.title == category
    end
    i_arr
  end
end

mybackpack/app/controllers/user_available_items_controller.rb
class UserAvailableItemsController < ApplicationController
  before_action :set_user_available_item, only: [:show, :edit, :update, :destroy]

  def index
    @user_available_items = current_user.user_available_items.all
    @categories = UserAvailableItem.item_categories(@user_available_items)
  end

  def show; end

  def new
    @user_available_item = UserAvailableItem.new
  end

  def edit; end

  def create
    @user_available_item = UserAvailableItem.new(user_available_item_params)
    @user_available_item.user_id = current_user.id

    respond_to do |format|
      if @user_available_item.save
        format.html { redirect_to @user_available_item, notice: 'User available item was successfully created.' }
        format.json { render :show, status: :created, location: @user_available_item }
      else
        format.html { render :new }
        format.json { render json: @user_available_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user_available_item.update(user_available_item_params)
        format.html { redirect_to @user_available_item, notice: 'User available item was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_available_item }
      else
        format.html { render :edit }
        format.json { render json: @user_available_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user_available_item.destroy
    respond_to do |format|
      format.html { redirect_to user_available_items_url, notice: 'User available item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user_available_item
    @user_available_item = UserAvailableItem.find(params[:id])
  end

  def user_available_item_params
    params.require(:user_available_item).permit(:item_id, :count)
  end
end

mybackpack/app/helpers/user_available_items_helper.rb
module UserAvailableItemsHelper
end

mybackpack/app/views/user_available_items/_form.html.erb
<%= form_with(model: user_available_item, local: true) do |form| %>
  <% if user_available_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_available_item.errors.count, "error") %> prohibited this user_available_item from being saved:</h2>

      <ul>
      <% user_available_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :item_id, value: 'Спорядження', class: 'bmd-label-floating' %>
    <%= form.select(:item_id, options_from_collection_for_select(Item.all.sort_by{ |c| c.title }, :id, :title), {}, {:class => 'form-control'})%>
  </div>

  <div class="form-group">
    <%= form.label :count, value: 'Кількість', class: 'bmd-label-floating' %>
    <%= form.number_field :count, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit value: 'Додати', class: 'btn btn-primary btn-raised' %>
  </div>
<% end %>

mybackpack/app/views/user_available_items/edit.html.erb
<h1>Редагувати спорядження</h1>

<%= render 'form', user_available_item: @user_available_item %>

<!-- <%= link_to 'Show', @user_available_item %> | -->
<%= link_to 'Повернутися', user_available_items_path %>

mybackpack/app/views/user_available_items/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="row">

<div class="col-md-2"></div>
<div class="col-md-3">
<h3 style="margin-bottom: 30px; margin-left: -50px">Профіль</h3>
</div>
<div class="col-md-7"></div>

<div>

<div class="row" style="width: 900px; align-content: center;">
<div class="col-md-2"></div>
<div class="col-md-3">
  <!-- <p><%= link_to 'User available items', user_available_items_path %></p> -->
  <!-- <p><%= link_to 'User favorite foods', user_favorite_foods_path %></p> -->
<!--   <p><%= link_to 'User routes', user_routes_path %></p>
  <p><%= link_to 'User articles', user_articles_path %></p> -->

  <p style="font-size: 20px"><%= link_to 'Мої дані', profile_path(current_user.id) %></p>
  <p style="font-size: 20px"><%= link_to 'Мої статті', user_articles_path %></p>
  <p style="font-size: 20px"><%= link_to 'Мої маршрути', user_routes_path %></p>
  <p style="font-size: 20px"><%= link_to 'Моє спродяження', user_available_items_path %></p>
</div>

<div class="col-md-7" >

  <h4 style="margin-bottom: 30px">Моє спорядження</h4>

  <%= link_to 'Додати річ', new_user_available_item_path %>
  <p style="margin-bottom: 30px"></p>

  <% @categories.each do |category| %>
  <p style="font-size: 16px; font-weight: bold"><%= category %></p>
  <table style="border-bottom: 1px solid black">
    <thead>
      <tr>
        <th style="width: 250px; font-size: 12px;">Назва</th>
        <th style="padding: 4px; font-size: 12px;">Кількість</th>
        <th style="padding: 4px; font-size: 12px;">Вага, кг</th>
        <th style="padding: 4px; font-size: 12px;">Індивідуальність</th>
        <th style="padding: 4px"></th>
      </tr>
    </thead>

    <tbody>
      <% UserAvailableItem.category_items(@user_available_items, category).each do |i| %>
        <tr style="border-bottom: 1px solid black">
          <td><%= i.item.title %></td>
          <td><%= i.count %></td>
          <td><%= i.item.weight %></td>
          <td>
            <% if i.item.individualy %>
              індивідуальна
            <% else %>
              групова
            <% end %>
          </td>
          <td><%= link_to 'Детальніше', item_path(i.item) %>
          <%= link_to 'Редагувати', edit_user_available_item_path(i) %>
          <%= link_to 'Видалити', i, method: :delete, data: { confirm: 'Ви впевнені?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
<% end %>

<br>

</div>
</div>

mybackpack/app/views/user_available_items/new.html.erb
<h1>Додати спорядження</h1>

<%= render 'form', user_available_item: @user_available_item %>

<%= link_to 'Повернутися', user_available_items_path %>

mybackpack/app/views/user_available_items/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= link_to 'Edit', edit_user_available_item_path(@user_available_item) %> |
<%= link_to 'Back', user_available_items_path %>